Fixing pure python tests
HQSquantumsimulations/reusable_workflows pull request #19
Opened 2023-03-01 11:59 UTC by kbarkhqs

2023-03-01 12:34 UTC, nfwvogt requested changes

2023-03-01 13:12 UTC, nfwvogt requested changes

2023-03-01 13:12 UTC, nfwvogt commented on .github/workflows/reusable_tests_pure_python.yml
> +          pip install .
This is now in the wrong order

2023-03-01 13:12 UTC, nfwvogt commented on .github/workflows/reusable_tests_pure_python.yml
>            pytest tests/
With this we might again run into the issue that in the import statements of the python tests the folder versions of the Python files will be imported and not the just installed package. 

We could instead cd into tests and run pytest inside that folder.

2023-03-01 14:39 UTC, kbarkhqs commented on .github/workflows/reusable_tests_pure_python.yml
> +          pip install .
Ah thank you

2023-03-02 16:17 UTC, nfwvogt approved these changes

2023-03-02 16:37 UTC, merged